"""Declare runtime dependencies

These are needed for local dev, and users must install them as well.
See https://docs.bazel.build/versions/main/skylark/deploying.html#dependencies
"""

load("//react_native/private:toolchains_repo.bzl", "PLATFORMS", "toolchains_repo")
load("//react_native/private:versions.bzl", "TOOL_VERSIONS")

_DOC = "Fetch external tools needed for react_native toolchain"
_ATTRS = {
    "react_native_version": attr.string(mandatory = True, values = TOOL_VERSIONS.keys()),
    "platform": attr.string(mandatory = True, values = PLATFORMS.keys()),
}

def _react_native_repo_impl(repository_ctx):
    url = "https://github.com/someorg/someproject/releases/download/v{0}/react_native-{1}.zip".format(
        repository_ctx.attr.react_native_version,
        repository_ctx.attr.platform,
    )
    repository_ctx.download_and_extract(
        url = url,
        integrity = TOOL_VERSIONS[repository_ctx.attr.react_native_version][repository_ctx.attr.platform],
    )
    ext = ".exe" if repository_ctx.attr.platform.find("windows") >= 0 else ""
    build_content = """# Generated by react_native/repositories.bzl
load("@rules_react_native//react_native:toolchain.bzl", "react_native_toolchain")

react_native_toolchain(
    name = "react_native_toolchain",
    target_tool = "react_native_tool{ext}",
)
""".format(ext = ext)

    # Base BUILD file for this repository
    repository_ctx.file("BUILD.bazel", build_content)

    # Bazel <8.3.0 lacks rctx.repo_metadata
    if not hasattr(repository_ctx, "repo_metadata"):
        return None

    # https://bazel.build/rules/lib/builtins/repository_ctx#repo_metadata
    # Indicate whether the repo can be reproducibly refetched, allowing it
    # to be cached across workspaces.
    return repository_ctx.repo_metadata(reproducible = True)

react_native_repositories = repository_rule(
    _react_native_repo_impl,
    doc = _DOC,
    attrs = _ATTRS,
)

# Wrapper macro around everything above, this is the primary API
def react_native_register_toolchains(name, **kwargs):
    """Convenience macro for users which does typical setup.

    - create a repository for each built-in platform like "react_native_linux_amd64"
    - TODO: create a convenience repository for the host platform like "react_native_host"
    - create a repository exposing toolchains for each platform like "react_native_platforms"
    Users can avoid this macro and do these steps themselves, if they want more control.

    Args:
        name: base name for all created repos, like "react_native1_14"
        **kwargs: passed to each react_native_repositories call
    """
    for platform in PLATFORMS.keys():
        react_native_repositories(
            name = name + "_" + platform,
            platform = platform,
            **kwargs
        )

    toolchains_repo(
        name = name + "_toolchains",
        user_repository_name = name,
    )
